# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ylam <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/25 11:44:37 by ylam              #+#    #+#              #
#    Updated: 2022/01/25 11:44:43 by ylam             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_isprint.c \
	ft_isascii.c \
	ft_isalnum.c \
	ft_isdigit.c \
	ft_isalpha.c \
	ft_atoi.c \
	ft_bzero.c	\
	ft_calloc.c	\
	ft_memchr.c	\
	ft_memcmp.c	\
	ft_memcpy.c	\
	ft_memmove.c	\
	ft_memset.c	\
	ft_strchr.c	\
	ft_strdup.c	\
	ft_strlcat.c	\
	ft_strlcpy.c	\
	ft_strlen.c	\
	ft_strncmp.c	\
	ft_strnstr.c	\
	ft_strrchr.c	\
	ft_tolower.c	\
	ft_toupper.c	\
	ft_substr.c \
	ft_strjoin.c \
	ft_strtrim.c \
	ft_split.c \
	ft_itoa.c \
	ft_strmapi.c \
	ft_putchar_fd.c \
	ft_striteri.c \
	ft_putstr_fd.c \
	ft_putendl_fd.c \
	ft_putnbr_fd.c \
	get_next_line.c \
	ifchar.c \
	ifdcm.c \
	ifhex.c \
	ifpercent.c \
	ifpointer.c \
	ifstr.c \
	ifunsigned.c \
	ft_printf.c \

BONUS =	ft_lstnew.c \
	ft_lstsize.c \
	ft_lstlast.c \
	ft_lstiter.c \
	ft_lstclear.c \
	ft_lstdelone.c \
	ft_lstadd_back.c \
	ft_lstadd_front.c \

OBJS	=	$(SRCS:.c=.o)

OBJSB = $(BONUS:.c=.o)

CC		=	gcc

RM		=	rm -rf

NAME	=	libft.a

CFLAGS	=	-Wall -Wextra -Werror

AR		= 	ar rc

all :	$(NAME)

$(NAME) :	$(OBJS)
			$(AR) $(NAME) $(OBJS)

clean :
			$(RM) $(OBJS) $(OBJSB)

fclean :	clean
			$(RM) $(NAME)

re :		fclean all

bonus : $(OBJS) $(OBJSB)
				$(AR) $(NAME) $(OBJS) $(OBJSB)
